package io.github.shaksternano.borgar.discord.interaction.message

import io.github.shaksternano.borgar.discord.interaction.DiscordInteractionCommand
import net.dv8tion.jda.api.events.interaction.command.MessageContextInteractionEvent

interface DiscordMessageInteractionCommand : DiscordInteractionCommand<MessageContextInteractionEvent>
