package com.shakster.borgar.discord.interaction.message

import com.shakster.borgar.discord.interaction.DiscordInteractionCommand
import net.dv8tion.jda.api.events.interaction.command.MessageContextInteractionEvent

interface DiscordMessageInteractionCommand : DiscordInteractionCommand<MessageContextInteractionEvent>
