name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      POSTGRESQL_URL: jdbc:postgresql://localhost:5432/postgres
      POSTGRESQL_PORTS: 5432:5432
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Create .env file for Docker Compose
        run: |
          touch .env
          echo POSTGRESQL_PORTS=POSTGRESQL_PORTS >> .env
          echo POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME >> .env
          echo POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD >> .env

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests
        run: ./gradlew test --stacktrace --parallel

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: |
            build/reports/tests/test/
