name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      POSTGRES_URL: jdbc:postgresql://localhost:5332/postgres
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Create .env file for Docker Compose
        run: |
          touch .env
          echo POSTGRES_USERNAME=$POSTGRES_USERNAME >> .env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests
        run: ./gradlew test --stacktrace --parallel

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: |
            build/reports/tests/test/
