name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Run tests
        run: ./gradlew test --stacktrace --parallel

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: |
            build/reports/tests/test/
